jobs:
  build:
    name: Latest Java LTS Build and Verify
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out Git repository
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up Java and Maven
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: 21
    - continue-on-error: true
      name: Install Zig
      uses: goto-bus-stop/setup-zig@v2
    - continue-on-error: true
      name: Cross compile using Zig
      run: ./cross-compile.sh
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B verify -DgcRecordWrites=1000
    - continue-on-error: true
      name: Store built native libraries for later jobs
      uses: actions/upload-artifact@v3
      with:
        name: native-libraries
        path: 'src/main/resources/org/lmdbjava/*.so

          src/main/resources/org/lmdbjava/*.dll

          '
    - continue-on-error: true
      name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v3
  compatibility-checks:
    name: Java ${{ matrix.java }} on ${{ matrix.os }} Compatibility
    needs:
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out Git repository
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up Java and Maven
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Fetch built native libraries
      uses: actions/download-artifact@v3
      with:
        name: native-libraries
        path: src/main/resources/org/lmdbjava
    - continue-on-error: true
      name: Execute verifier
      run: mvn -B test -Dtest=VerifierTest -DverificationSeconds=10
    - continue-on-error: true
      if: failure()
      name: Upload Surefire reports on test failure
      uses: actions/upload-artifact@v3
      with:
        name: surefire-test-log
        path: target/surefire-reports
    strategy:
      matrix:
        java:
        - 8
        - 11
        - 17
        - 21
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
  deploy:
    if: github.event_name == 'push'
    name: Deploy to OSSRH
    needs:
    - build
    - compatibility-checks
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out Git repository
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up Java and Maven
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.gpg_private_key }}
        java-version: 8
        server-id: ossrh
        server-password: MAVEN_CENTRAL_TOKEN
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      name: Install Zig
      uses: goto-bus-stop/setup-zig@v2
    - continue-on-error: true
      name: Cross compile using Zig
      run: ./cross-compile.sh
    - continue-on-error: true
      env:
        MAVEN_CENTRAL_TOKEN: ${{ secrets.nexus_password }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.gpg_passphrase }}
        MAVEN_USERNAME: ${{ secrets.nexus_username }}
      name: Publish Maven package
      run: mvn -B -Possrh-deploy deploy -DskipTests
    - continue-on-error: true
      if: failure()
      name: Debug settings.xml
      uses: actions/upload-artifact@v3
      with:
        name: settings.xml
        path: $HOME/.m2/settings.xml
name: Maven Build and Deployment
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
